apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clipped
  namespace: clipped
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - clipped.chat
      secretName: clipped-chat-tls
  rules:
    - host: clipped.chat
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clipped
                port:
                  number: 80
